# guestbook-ui-service.yaml (modified for LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    app.kubernetes.io/name: guestbook-ui
    app.kubernetes.io/instance: guestbook-ui
spec:
  # =========================================================
  # 💡 THE CRITICAL CHANGE: Sets up a Cloud Provider Load Balancer
  # =========================================================
  type: LoadBalancer 
  selector:
    app: guestbook-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
